version: '3'

services:
  nacos-1.3:
    container_name: nacos-1.3
    image: nacos/nacos-server:1.3.1
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    volumes:
      - ./standalone-logs/:/home/nacos/logs
      - ./software/nacos/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
    #restart: on-failure

